### ISSUE TITLE
Speedtest and Cloudflair same issue

### ISSUE THREAD

**Issue by nicksimoneau** [bitfocus/companion-module-generic-speedtest#12]
Hi I just tryed the speedtest connections and there is my result:

error: Module registration failed Error: Call timed out
    at t.IpcWrapper.sendWithCb (C:\Program Files\Companion\resources\bundled-modules\generic-speedtest\main.js:2:1097858)
    at C:\Program Files\Companion\resources\bundled-modules\generic-speedtest\main.js:2:1090903
Starting up module class: c
Sentry disabled

Companion version: 3.2.0 (3.2.0+6663-stable-b83f412f)
Windows 10 - x64 - 22H2

**Comment by nicksimoneau** [comment]
> Hi I just tryed the speedtest connections and there is my result:
> 
> error: Module registration failed Error: Call timed out at t.IpcWrapper.sendWithCb (C:\Program Files\Companion\resources\bundled-modules\generic-speedtest\main.js:2:1097858) at C:\Program Files\Companion\resources\bundled-modules\generic-speedtest\main.js:2:1090903 Starting up module class: c Sentry disabled
> 
> Companion version: 3.2.0 (3.2.0+6663-stable-b83f412f) Windows 10 - x64 - 22H2

Nevermind I have reboot companion and everything seems good :)
